---
- name: Start container nginx
  docker_container:
    name: nginx
    image: aurora0/kpilab
    privileged: yes
    command: ["nginx"]
    ports:
      - "80:80"

- name: Start container watchtower
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    privileged: yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock